### ISSUE TITLE
type errors when running demo

### ISSUE THREAD

**Issue by andykais** [astrodon/astrodon#6] opened 2022-01-06 19:10 UTC
`deno run -A --unstable --reload https://raw.githubusercontent.com/astrodon/astrodon/main/demo/demo.ts`
```
Check https://raw.githubusercontent.com/astrodon/astrodon/main/demo/demo.ts
error: TS2694 [ERROR]: Namespace 'Deno' has no exported member 'UnsafePointer'.
  private app_ptr: Deno.UnsafePointer | undefined;
                        ~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/astrodon/astrodon/main/mod.ts:26:25

TS2322 [ERROR]: Type '"pointer"' is not assignable to type 'NativeType | "buffer"'.
      create_app: { parameters: ["pointer", "usize"], result: "pointer" },
                                 ~~~~~~~~~
    at https://raw.githubusercontent.com/astrodon/astrodon/main/mod.ts:43:34

TS2322 [ERROR]: Type '"pointer"' is not assignable to type 'NativeType'.
      create_app: { parameters: ["pointer", "usize"], result: "pointer" },
                                                      ~~~~~~
    at https://raw.githubusercontent.com/astrodon/astrodon/main/mod.ts:43:55

TS2322 [ERROR]: Type '"pointer"' is not assignable to type 'NativeType | "buffer"'.
      run_app: { parameters: ["pointer"], result: "pointer" },
                              ~~~~~~~~~
    at https://raw.githubusercontent.com/astrodon/astrodon/main/mod.ts:44:31

TS2322 [ERROR]: Type '"pointer"' is not assignable to type 'NativeType'.
      run_app: { parameters: ["pointer"], result: "pointer" },
                                          ~~~~~~
    at https://raw.githubusercontent.com/astrodon/astrodon/main/mod.ts:44:43

TS2322 [ERROR]: Type '"pointer"' is not assignable to type 'NativeType | "buffer"'.
        parameters: ["pointer", "usize", "pointer"],
                     ~~~~~~~~~
    at https://raw.githubusercontent.com/astrodon/astrodon/main/mod.ts:46:22

TS2322 [ERROR]: Type '"pointer"' is not assignable to type 'NativeType | "buffer"'.
        parameters: ["pointer", "usize", "pointer"],
                                         ~~~~~~~~~
    at https://raw.githubusercontent.com/astrodon/astrodon/main/mod.ts:46:42

TS2322 [ERROR]: Type '"pointer"' is not assignable to type 'NativeType'.
        result: "pointer",
        ~~~~~~
    at https://raw.githubusercontent.com/astrodon/astrodon/main/mod.ts:47:9

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'UnsafePointer'.
    ) as Deno.UnsafePointer;
              ~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/astrodon/astrodon/main/mod.ts:61:15

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'UnsafePointer'.
    this.app_ptr = this.lib.symbols.run_app(this.app_ptr) as Deno.UnsafePointer;
                                                                  ~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/astrodon/astrodon/main/mod.ts:62:67

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'UnsafePointer'.
    ) as Deno.UnsafePointer;
              ~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/astrodon/astrodon/main/mod.ts:69:15

Found 11 errors.
```

**Comment by marc2332** [comment] 2022-01-06 19:16
I am sure you are using an "old" version. Try updating to v1.17.2 :D

**Comment by hironichu** [comment] 2022-01-13 06:18
> I am pretty confident you are using an "old" version. Try updating to v1.17.2 :D

Yep I can confirm, this is because old version of Deno !

**Comment by andykais** [comment] 2022-01-13 14:18
maybe! I just upgraded deno to 1.17.2 and I see this now for https://github.com/astrodon/astrodon/tree/main/examples/hello_world:
```
Check file:///Users/andrew/Code/scratchwork/astrodon/examples/hello_world/demo.ts
Check file:///Users/andrew/Code/scratchwork/astrodon/examples/hello_world/astrodon.config.ts
error: Uncaught (in promise) TypeError: Path must be a string. Received undefined
    throw new TypeError(
          ^
    at assertPath (https://deno.land/std@0.121.0/path/_util.ts:18:11)
    at join (https://deno.land/std@0.121.0/path/posix.ts:111:5)
    at getLibraryLocation (file:///Users/andrew/Code/scratchwork/astrodon/modules/astrodon/utils.ts:65:19)
    at async Function.new (file:///Users/andrew/Code/scratchwork/astrodon/modules/astrodon/mod.ts:58:21)
    at async file:///Users/andrew/Code/scratchwork/astrodon/examples/hello_world/demo.ts:15:13
```

**Comment by marc2332** [comment] 2022-01-13 14:29
Unfortunately, MacOS is not supported yet D: 

Only Windows and Linux for now. I am gonna close this, I just opened https://github.com/astrodon/astrodon/issues/11

**Comment by pavi2410** [comment] 2022-01-21 06:15
Similar error here

```
❯ deno run -A --unstable --reload https://raw.githubusercontent.com/astrodon/astrodon/main/examples/hello_world/demo.ts
...
error: TS2345 [ERROR]: Argument of type '[Uint8Array, number]' is not assignable to parameter of type '[...{ [K in keyof S[string]["parameters"]]: StaticForeignFunctionParameter<S[string]["parameters"][K]>; }]'.
  Source has 2 element(s) but target allows only 1.
      ...encode(context),
      ~~~~~~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/astrodon/astrodon/main/modules/astrodon/mod.ts:88:7

TS2345 [ERROR]: Argument of type '[UnsafePointer]' is not assignable to parameter of type '[...{ [K in keyof S[string]["parameters"]]: StaticForeignFunctionParameter<S[string]["parameters"][K]>; }]'.
  Source provides no match for variadic element at position 0 in target.
    this.app_ptr = this.lib.symbols.run_app(this.app_ptr) as Deno.UnsafePointer;
                                            ~~~~~~~~~~~~
    at https://raw.githubusercontent.com/astrodon/astrodon/main/modules/astrodon/mod.ts:90:45

TS2345 [ERROR]: Argument of type '[Uint8Array, number, UnsafePointer | undefined]' is not assignable to parameter of type '[...{ [K in keyof S[string]["parameters"]]: StaticForeignFunctionParameter<S[string]["parameters"][K]>; }]'.
  Source has 3 element(s) but target allows only 1.
      ...encode(msg),
      ^
    at https://raw.githubusercontent.com/astrodon/astrodon/main/modules/astrodon/mod.ts:95:7

Found 3 errors.
```
```
❯ deno --version
deno 1.18.0 (release, x86_64-pc-windows-msvc)
v8 9.8.177.6
typescript 4.5.2
```

**Comment by marc2332** [comment] 2022-01-21 12:10
> Similar error here
> 
> ```
> ❯ deno run -A --unstable --reload https://raw.githubusercontent.com/astrodon/astrodon/main/examples/hello_world/demo.ts
> ...
> error: TS2345 [ERROR]: Argument of type '[Uint8Array, number]' is not assignable to parameter of type '[...{ [K in keyof S[string]["parameters"]]: StaticForeignFunctionParameter<S[string]["parameters"][K]>; }]'.
>   Source has 2 element(s) but target allows only 1.
>       ...encode(context),
>       ~~~~~~~~~~~~~~~~~~
>     at https://raw.githubusercontent.com/astrodon/astrodon/main/modules/astrodon/mod.ts:88:7
> 
> TS2345 [ERROR]: Argument of type '[UnsafePointer]' is not assignable to parameter of type '[...{ [K in keyof S[string]["parameters"]]: StaticForeignFunctionParameter<S[string]["parameters"][K]>; }]'.
>   Source provides no match for variadic element at position 0 in target.
>     this.app_ptr = this.lib.symbols.run_app(this.app_ptr) as Deno.UnsafePointer;
>                                             ~~~~~~~~~~~~
>     at https://raw.githubusercontent.com/astrodon/astrodon/main/modules/astrodon/mod.ts:90:45
> 
> TS2345 [ERROR]: Argument of type '[Uint8Array, number, UnsafePointer | undefined]' is not assignable to parameter of type '[...{ [K in keyof S[string]["parameters"]]: StaticForeignFunctionParameter<S[string]["parameters"][K]>; }]'.
>   Source has 3 element(s) but target allows only 1.
>       ...encode(msg),
>       ^
>     at https://raw.githubusercontent.com/astrodon/astrodon/main/modules/astrodon/mod.ts:95:7
> 
> Found 3 errors.
> ```
> 
> ```
> ❯ deno --version
> deno 1.18.0 (release, x86_64-pc-windows-msvc)
> v8 9.8.177.6
> typescript 4.5.2
> ```

Weird, we are looking into it. Meanwhile, you can run it with `--no-check`:

```
deno run -A --unstable --reload --no-check https://raw.githubusercontent.com/astrodon/astrodon/main/examples/hello_world/demo.ts
```

**Comment by marc2332** [comment] 2022-01-21 13:00
> Similar error here
> 
> ```
> ❯ deno run -A --unstable --reload https://raw.githubusercontent.com/astrodon/astrodon/main/examples/hello_world/demo.ts
> ...
> error: TS2345 [ERROR]: Argument of type '[Uint8Array, number]' is not assignable to parameter of type '[...{ [K in keyof S[string]["parameters"]]: StaticForeignFunctionParameter<S[string]["parameters"][K]>; }]'.
>   Source has 2 element(s) but target allows only 1.
>       ...encode(context),
>       ~~~~~~~~~~~~~~~~~~
>     at https://raw.githubusercontent.com/astrodon/astrodon/main/modules/astrodon/mod.ts:88:7
> 
> TS2345 [ERROR]: Argument of type '[UnsafePointer]' is not assignable to parameter of type '[...{ [K in keyof S[string]["parameters"]]: StaticForeignFunctionParameter<S[string]["parameters"][K]>; }]'.
>   Source provides no match for variadic element at position 0 in target.
>     this.app_ptr = this.lib.symbols.run_app(this.app_ptr) as Deno.UnsafePointer;
>                                             ~~~~~~~~~~~~
>     at https://raw.githubusercontent.com/astrodon/astrodon/main/modules/astrodon/mod.ts:90:45
> 
> TS2345 [ERROR]: Argument of type '[Uint8Array, number, UnsafePointer | undefined]' is not assignable to parameter of type '[...{ [K in keyof S[string]["parameters"]]: StaticForeignFunctionParameter<S[string]["parameters"][K]>; }]'.
>   Source has 3 element(s) but target allows only 1.
>       ...encode(msg),
>       ^
>     at https://raw.githubusercontent.com/astrodon/astrodon/main/modules/astrodon/mod.ts:95:7
> 
> Found 3 errors.
> ```
> 
> ```
> ❯ deno --version
> deno 1.18.0 (release, x86_64-pc-windows-msvc)
> v8 9.8.177.6
> typescript 4.5.2
> ```

Should be ok now! Try again and let me know if it works 👌🏻 :D

**Comment by pavi2410** [comment] 2022-01-21 13:04
Cool. Works now 👍 

![image](https://user-images.githubusercontent.com/28837746/150531704-d35a6eca-739c-4f87-a423-5f6cec1af268.png)

**Comment by marc2332** [comment] 2022-01-21 13:13
Awesome! 🦕

**Closed by marc2332** 2022-01-21 13:13 UTC
Labels: help wanted
